version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # Adicione outros parâmetros do docker-compose específicos do submodulo2 aqui
